# BSD 3-Clause License
# Copyright (c) 2022, GM Consult Pty Ltd
# Copyright (c) 2001, Dr Martin Porter,
# Copyright (c) 2002, Richard Boulton.
# All rights reserved.

include: package:lints/recommended.yaml

linter:
  rules:
    - sort_pub_dependencies
    - always_put_required_named_parameters_first
    - public_member_api_docs
    - type_annotate_public_apis
