# BSD 3-Clause License
# Copyright (c) 2022, GM Consult Pty Ltd
# All rights reserved.

# Porter stemmer algorithm is Copyright (c) 2001, Dr Martin Porter, and
# Copyright (c) 2002, Richard Boulton, all rights reserved.

name: porter_2_stemmer
description: Reduce a word to its root form using the Porter English stemming algorithm.
version: 2.0.0-1
repository: https://github.com/GM-Consult-Pty-Ltd/porter_2_stemmer
homepage: https://github.com/GM-Consult-Pty-Ltd
issue_tracker: https://github.com/GM-Consult-Pty-Ltd/porter_2_stemmer/issues

environment:
  sdk: '>=2.17.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.1
