name: porter_2_stemmer
description: DART implementation of the Porter stemming algorithm, used for reducing a word to its word stem, base or root form.
version: 0.0.1
repository: https://github.com/GerhardMalan/porter_2_stemmer
homepage: https://github.com/GerhardMalan/porter_2_stemmer

environment:
  sdk: '>=2.17.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
